apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::520668085636:role/eksctl-pratik-cluster-nodegroup-ng-NodeInstanceRole-foFhwjFudhHf
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-07T03:59:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1298"
  uid: b0f4d21f-fc39-46d6-8e12-5a0b5feeacec
