apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::520668085636:role/eksctl-pratik-cluster-nodegroup-ng-NodeInstanceRole-foFhwjFudhHf
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: | # defining the mapRoles which been defined by the AWS EKS already
    - userarn: arn:aws:iam::520668085636:user/eks-trainee
      username: eks-trainee
    - userarn: arn:aws:iam::520668085636:user/eks-developer
      username: eks-developer
    - userarn: arn:aws:iam::520668085636:user/eks-cluster-superadmin
      groups:
        - system:masters
      username: eks-cluster-superadmin
kind: ConfigMap
metadata:
  name: aws-auth # 
  namespace: kube-system

