apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queueapp
  ports:
  - name: admin
    port: 8161
    protocol: TCP
    targetPort: 8161
    nodePort: 30010

  - name: endpoint
    port: 61616
    targetPort: 61616
    protocol: TCP

  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
  - name: rest
    port: 8080
    protocol: TCP
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8080
    protocol: TCP
    nodePort: 30030
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
  ports:
  - name: angular
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  type: NodePort



