apiVersion: v1
kind: Service
metadata:
  name: fleetman-nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30090
  type: NodePort
