apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp

  replicas: 2

  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
# selecting the document separator in yml to define the queue POD in this case 

apiVersion: v1
kind: Pod
metadata:
  name: queueapp
  labels:
    app: queueapp
spec:
  containers:
  - image: richardchesterwood/k8s-fleetman-queue:release1
    name: queueapp

