apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    protocol: TCP

  type: LoadBalancer


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queueapp
  ports:
  - name: admin
    port: 8161
    protocol: TCP

  - name: endpoint
    port: 61616
    protocol: TCP

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: rest
    port: 8080
    protocol: TCP

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
  - name: url
    port: 8080
    protocol: TCP

  type: ClusterIP
