apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        name: webapp
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queueapp
  template:
    metadata:
      labels:
        app: queueapp
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-queue:release2
        name: queueapp


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-position-tracker:release3
        name: position-tracker
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-simulator
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-position-simulator:release2
        name: position-simulator
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-api-gateway:release2
        name: api-gateway
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

