apiVersion: v1 # here the apivrsion being as v1 as the configMap belong to the core group
kind: Secret # here creating the kubernetes object of type Secret
metadata: # here providing the name for the Secret as mongo-secret
  name: mongo-secret
type: Opaque # here as we are using the user defined secret we are using the Opaque
data: # like other kubernetes object has the spec field configMaps has the data field in this case
  # data field wioll going to take the key value pair as value
  password: cGFzc3dvcmQ=
  # herwe we are suing the base64 encoded code
