apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080

  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queueapp
spec:
  selector:
    app: queueapp
  ports:
  - name: http
    port: 8161
    targetPort: 8161
    protocol: TCP
    nodePort: 30010

  type: NodePort
