apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  minReadySeconds: 30
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
        name: webapp

---

apiVersion: v1
kind: Pod
metadata:
  name: queueapp
  labels:
    app: queueapp
spec:
  containers:
  - image: richardchesterwood/k8s-fleetman-queue:release1
    name: queueapp
