apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
    release: "0"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
# using the document separator here
apiVersion: v1
kind: Pod
metadata:
  name: webappnew
  labels:
    app: webappnew
    release: "0-5"
spec:
  containers:
  - name: webappnew
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
